Removal of 2nd Blip for job change
qbcore-framework/qb-truckerjob pull request #33
Opened 2022-08-23 17:45 UTC by mrdiamonddirt

**Describe Pull request**
Fixes Bug, where a blip doesn't get removed when changing jobs
fixes #31 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2022-08-23 23:39 UTC, tom-osborne requested changes

2022-08-23 23:39 UTC, tom-osborne commented on client/main.lua
>  	    ClearAllBlipRoutes()
Fix indentation here

2022-08-23 23:39 UTC, tom-osborne commented on client/main.lua
>      if TruckVehBlip then
Should probably check for `Truckerblip` too. Maybe separate them into separate if statements.

2022-08-24 16:13 UTC, tom-osborne commented on client/main.lua
>  	    ClearAllBlipRoutes()
Still indented

2022-08-24 17:05 UTC, tom-osborne commented
@mrdiamonddirt  https://github.com/qbcore-framework/qb-truckerjob/pull/33#discussion_r954005330 Fix this indentation and I'll merge.

2022-08-24 17:07 UTC, mrdiamonddirt commented on client/main.lua
>  	    ClearAllBlipRoutes()
sorry i thought i fixed it

2022-08-24 22:39 UTC, tom-osborne approved these changes

2022-08-24 22:40 UTC, merged