Complete the code to be compatible with the phone
qbcore-framework/qb-truckerjob pull request #6
Opened 2021-08-28 11:02 UTC by darknight2590

2021-08-28 11:27 UTC, darknight2590 commented
add this to player.lua
```
	PlayerData.metadata["jobtier"] = PlayerData.metadata["jobtier"] ~= nil and PlayerData.metadata["jobtier"] or {
		["trucker"] = 0,
	}
```
add this under PlayerData.metadata["phonedata]
```
	PlayerData.metadata["payslips"] = PlayerData.metadata["payslips"] ~= nil and PlayerData.metadata["payslips"] or {
		["trucker"] = 0
	}
```

add this in config.lua in qbcore
```

QBConfig.Tiers = {}
QBConfig.Tiers[1] = 100
QBConfig.Tiers[2] = 200
QBConfig.Tiers[3] = 300
QBConfig.Tiers[4] = 400
QBConfig.Tiers[5] = 500
```

2021-09-15 15:35 UTC, FreakOutModz requested changes
All variables should also start with a lower case and each additional word in upper case for a cleaner code.

2021-09-15 15:35 UTC, FreakOutModz commented on client/main.lua
> +													ClearAllBlipRoutes()
Why did you add so many spaces ? Please make the code look clean

2021-09-15 15:35 UTC, FreakOutModz commented on client/main.lua
> +    CurrentLocation.x = Config.Locations["stores"][location].coords.x
You can do:
`CurrentLocation.xyz = Config.Locations["stores"][location].coords.xyz`

2021-09-15 15:35 UTC, FreakOutModz commented on client/main.lua
> +    return returnn
returnn ? What... please name this correctly. That doesn't mean anything.

2021-09-15 15:35 UTC, FreakOutModz commented on client/main.lua
> +												TriggerServerEvent("qb-trucker:server:deliveryDone", CurrentLocation.dropcount)
So many spaces here too, plese make a clean code.

2021-09-15 15:35 UTC, FreakOutModz commented on client/main.lua
> +												local locationId = CurrentLocation.id;
Same for spaces here too, please correct all the code.

2021-11-21 02:47 UTC, closed without merging